name: Export Android and iOS
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build Android" ]
    types: 
      - completed
  push:
    # paths: 
    #   - '.github/workflows/godot_export_android_ios_project.yml'
    #   - './../*'
    branches: [ master ]
env:
  GITHUB_RELEASE: true
  EXPORTER_PATH: godot_exporter
  EXPORT_VERSION_NAME: debug
  # DEBUG_KEYSTORE_PATH: "https://github.com/vini-guerrero/godot_exporter/blob/master/keystores/debug.keystore?raw=true"
  # RELEASE_KEYSTORE_PATH: "https://github.com/vini-guerrero/godot_exporter/blob/master/keystores/mygame.keystore?raw=true"
jobs:
  export:
    name: Export and Upload Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GODOT_VERSIONS: [3.2.3]
        EXPORT_VERSION: [true, false]
    steps:
    - name: Set Version Name
      run: |
        [ "env.EXPORT_VERSION" == true ] && env.EXPORT_VERSION_NAME = "Release" || env.EXPORT_VERSION_NAME = "Debug"        
        echo $env.EXPORT_VERSION_NAME

    - uses: actions/checkout@v2
    
    - name: Setup ADB & Keystore
      # run: |
      #   wget -O debug.keystore ${{ env.DEBUG_KEYSTORE_PATH }}
      #   wget -O release.keystore ${{ env.RELEASE_KEYSTORE_PATH }}
      #   sudo chmod 777 -R /usr/bin
      #   mv debug.keystore /usr/bin
      #   mv release.keystore /usr/bin
      #   mv /usr/local/lib/android/sdk/platform-tools/adb /usr/bin
      
      run: |        
        sudo chmod 777 -R /usr/bin        
        mv /usr/local/lib/android/sdk/platform-tools/adb /usr/bin      
    
    - name: Setup Godot Environment and Project
      uses: vini-guerrero/godot-export@master
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        relative_project_path: ./
        use_preset_export_path: true
        create_release: ${{ env.GITHUB_RELEASE }}
        export_debug: ${{ matrix.EXPORT_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload iOS Summary
      uses: actions/upload-artifact@v2
      with:
        name: iOS-${{ env.EXPORT_VERSION_NAME }}
        path: /home/runner/work/${{ env.EXPORTER_PATH }}/builds/ios/iOS/

    - name: Upload Android Summary
      uses: actions/upload-artifact@v2
      with:
        name: Android-${{ env.EXPORT_VERSION_NAME }}
        path: /home/runner/work/${{ env.EXPORTER_PATH }}/builds/android/Android/

  
