name: Export for Android and iOS
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build Android" ]
    types: 
      - completed
  push:
    paths: 
      - '.github/workflows/export_android_ios_project.yml'
      - './**'
    branches: [ master ]
env:
  EXPORTER_PATH: godot_exporter
jobs:
  export:
    name: Export and Upload Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GODOT_VERSIONS: [3.2.3]
    steps:
    - uses: actions/checkout@v2
    - name: Set Up ADB & Keystore
      run: |
        keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
        sudo chmod 777 -R /usr/bin
        mv debug.keystore /usr/bin
        mv /usr/local/lib/android/sdk/platform-tools/adb /usr/bin
    - name: Export AdMob example to Android and iOS
      uses: gustavottc/godot-export@master
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        relative_project_path: ./
        use_preset_export_path: true
        create_release: false
        export_debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: iOS
        path: /home/runner/work/${{env.EXPORTER_PATH}}/builds/ios/iOS/

    - name: Upload Android artifact
      uses: actions/upload-artifact@v2
      with:
        name: Android
        path: /home/runner/work/${{env.EXPORTER_PATH}}/builds/android/Android/

  
